---
title: "Group 30 - University of California - domestic graduate enrollment (2008-2019)"
author: "Sam Rozal and Lauren Harris"
date: "11/13/2021"
output: html_document
---

```{r setup, include=TRUE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
library(tidyverse)
library(here)
```

```{r}
ucsb_grad <- read_csv(here("data","ucsb_grad_data.csv"))
```

```{r}
# bar graph of domestic enrollment at UCSB from 2008 to 2019 broken down by ethnicity
ggplot(data = ucsb_grad, aes(x = year_abbr, y = domestic_enrollment, fill = ethnicity)) +
  geom_col(position="fill") + # convert from absolute count to proportions
  labs(x="Year",
       y= "Propotion of Domestic Enrollment",
       title = "Ethnicities of Domestic UCSB Students (2008-2019)",
       fill = "Ethnicity or Race") + #rename axis labels
  theme_minimal() 

```

**Figure 1.** Proportions of ethnicities/races for domestically-enrolled students at the University of California, Santa Barbara (UCSB) from `r min(ucsb_grad$year_abbr)` to `r max(ucsb_grad$year_abbr)`. 